"""create market_snapshots

Revision ID: a955e60915f1
Revises: 
Create Date: 2026-01-02 00:21:09.817818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a955e60915f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('market_p_yes', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('model_p_yes', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('asof_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'asof_ts', name='uq_market_asof')
    )
    op.create_index(op.f('ix_market_snapshots_asof_ts'), 'market_snapshots', ['asof_ts'], unique=False)
    op.create_index(op.f('ix_market_snapshots_market_id'), 'market_snapshots', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_market_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_asof_ts'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
